### ISSUE TITLE
Renault Changed the Kamereon key

### ISSUE THREAD

**Issue by ldti** [chrisstaite/ZEServices#5]
New key is "Ae9FDWugRxZQAGm3Sxgk7uJn6Q4CGEA2".
Source:
hacf-fr/renault-api#181

**Comment by chrisstaite** [comment]
The Kamereon key is downloaded upon first launch from https://renault-wrd-prod-1-euw1-myrapp-one.s3-eu-west-1.amazonaws.com/configuration/android/config_en_GB.json.  There is an outstanding issue to allow selection of locale, but I'm yet to determine how to perform this.

**Comment by ldti** [comment]
The Kamereon key in this file is no longer valid!

**Comment by chrisstaite** [comment]
That file provides much of the configuration for the communications, so a modification of the key only is difficult to enact.

```
                            val servers = response.getJSONObject("servers")
                            val kamareon = servers.getJSONObject("wiredProd")
                            val kamareonUrl = kamareon.getString("target")
                            val kamareonApi = kamareon.getString("apikey")
                            val gigya = servers.getJSONObject("gigyaProd")
                            val gigyaUrl = gigya.getString("target")
                            val gigyaApi = gigya.getString("apikey")```

**Comment by ldti** [comment]
maybe this should work?
val kamareonApi = "Ae9FDWugRxZQAGm3Sxgk7uJn6Q4CGEA2" ?

a simple static value, for now..

**Comment by chrisstaite** [comment]
I feel significantly more needs to be modified:
```
            val kamareonUrl = "https://api-wired-prod-1-euw1.wrd-aws.com"
            val kamareonApi = "oF09WnKqvBDcrQzcW1rJNpjIuy7KdGaB"
            val gigyaUrl = "https://accounts.eu1.gigya.com"
            val gigyaApi = "3_4LKbCcMMcvjDm3X89LU4z4mNKYKdl_W0oD9w-Jvih21WqgJKtFZAnb9YdUgWT9_a"
```

**Comment by ldti** [comment]
In my prtg script, changing the kamereon key was enough.
I don't think anything else changed.



Sent from my Galaxy



-------- Original message --------

**Comment by chrisstaite** [comment]
I think it's a phased change, but those are the currently used production servers by the Renault services.

**Comment by ldti** [comment]
OK, can you try the changes?
I don't have an android dev environment to test this..



Sent from my Galaxy

**Comment by chrisstaite** [comment]
You're right, those values are also invalid.  I will have to research further how the values are updated.  There's also the outstanding issue that the /charges endpoint is now returning a 403 error also which I can't determine.

**Comment by ldti** [comment]
Got it.



Sent from my Galaxy

**Comment by ECOM-Engineering** [comment]
Yesterday 2022-03-17 I also got 403 error. Here are the new keys (Switzerland only?):
C_GIGYA_URL = "https://accounts.eu1.gigya.com"
C_GIGYA_API_ID = "3_UyiWZs_1UXYCUqK_1n7l7l44UiI_9N9hqwtREV0-UYA_5X7tOV-VKvnGxPBww4q2"
C_KAMERON_URL = "https://api-wired-prod-1-euw1.wrd-aws.com"
C_KAMERON_API = "VAX7XYKGfa92yMvXculCkEFyfZbuM7Ss"  # new since 2022-03-17

thanks to https://gist.github.com/mountbatt/772e4512089802a2aa2622058dd1ded7  !

**Comment by donnels** [comment]
> Yesterday 2022-03-17 I also got 403 error. Here are the new keys (Switzerland only?): C_GIGYA_URL = "https://accounts.eu1.gigya.com" C_GIGYA_API_ID = "3_UyiWZs_1UXYCUqK_1n7l7l44UiI_9N9hqwtREV0-UYA_5X7tOV-VKvnGxPBww4q2" C_KAMERON_URL = "https://api-wired-prod-1-euw1.wrd-aws.com" C_KAMERON_API = "VAX7XYKGfa92yMvXculCkEFyfZbuM7Ss" # new since 2022-03-17
> 
> thanks to https://gist.github.com/mountbatt/772e4512089802a2aa2622058dd1ded7 !

I tried the https://renault-wrd-prod-1-euw1-myrapp-one.s3-eu-west-1.amazonaws.com/configuration/android/config_en_GB.json link and got a different kemereo api key that does not match the above and does not work for me. 
I tried the above VAX7... one which worked fine. So first off thanks for the VAX7 key and then the follow up:
How do I get to that key when it changes next?

I also cross checked a few languages and countries and the json link above always came back with the same, non-working, api key. Is the VAX7 key extracted with a further step?
