### ISSUE TITLE
Stop charging at x%

### ISSUE THREAD

**Issue by Atsche1** [chrisstaite/ZEServices#6]
Hello,
can you please integrate a feature to the app, similar to a charge shedule but so that the battery is only charged to a specific percentage.
A simple, additional activation button with a control wheel for the percentage would be great. 
Thanks a lot!

**Comment by chrisstaite** [comment]
This is impossible with the software on the car unfortunately

**Comment by jumpjack** [comment]
I think this could be implemented, as long as the app remains active and connected to network in background to monitor battery status:  there are two possible way to stop the charge:
- by setting charge method from "always" to "scheduled" using endpoint /actions/charge-mode with this payload:
```
{
    "data": {
        "type": "ChargeMode",
        "attributes": {
            "action": "schedule_mode"
        }
    }
}
```

- by using endpoint /actions/charge-start with this payload:

```
{
    "data": {
        "type": "ChargingStart",
        "attributes": {
            "action": "stop"
        }
    }
}
```

To avoid "over quota" error from Reanult servers, I suggest to monitor battery charge status just once per minute.
